//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApplication_Midterm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieCategory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Director { get; set; }
        public string Rating { get; set; }
        public string Trailor_Link { get; set; }
        public string Category { get; set; }
        public string Image { get; set; }
        public string Stars { get; set; }
        public string Gross { get; set; }
        public string Votes { get; set; }
        public string Time { get; set; }
        public string Description { get; set; }
    }
}
